# CISC7204 Assignment 01

**Submitted by:** Xiji Hang (MC646933).

## Module 01 · Lab 01 — Importing automobile data

**Collaborators:** Xiji Hang (MC646933) and Xiaoyu Guo (MC648131).  
**Contribution:** All laboratory work is completed jointly.

**Source:** Adapted from the supplied IBM / Skills Network teaching notebook; original author credits are retained below. The source template is preserved separately.

**Execution:** Local Anaconda / Jupyter; results in this working copy are generated by executing its code. Input: `auto.csv`, the unchanged dataset snapshot specified by this lab.

**Dataset source:** [auto.csv](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv) (snapshot accessed 15 September 2026). Each row describes one automobile configuration with its specifications and listed price.

# Importing Dataset



## Objectives

After completing this lab you will be able to:

-   Acquire data in various ways
-   Obtain insights from data with Pandas library

<h2>Table of Contents</h2>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ol>
    <li><a href="#Data-Acquisition">Data Acquisition</a>
    <li><a href="#Basic-Insights-from-the-Data-set">Basic Insights from the Data set</a></li>
</ol>


</div>
<hr>

# Data Acquisition
<p>
A data set is typically a file containing data stored in one of several formats. Common file formats containing data sets include: .csv, .json, .xlsx etc. The data set can be stored in different places, on your local machine, on a server or a websiite, cloud storage and so on.<br>

To analyse data in a Python notebook, we need to bring the data set into the notebook. In this section, you will learn how to load a data set into our Jupyter Notebook.<br>

In our case, the Automobile Data set is an online source, and it is in a CSV (comma separated value) format. Let's use this data set as an example to practice reading data.
<ul>
    <li>Data source: <a href="https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data" target="_blank">https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data</a></li>
    <li>Data type: csv</li>
</ul>
The Pandas Library is a very popular and very useful tool that enables us to read various datasets into a data frame; our Jupyter notebook platforms have a built-in <b>Pandas Library</b> so that all we need to do is import Pandas without installing.
</p>

In [1]:
from pathlib import Path
import sys
import numpy as np
import pandas as pd
from IPython.display import display, Markdown
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 40)
pd.set_option('display.precision', 4)
def locate_dataset(filename):
    # Accept a flat submission, the bundle root, or the notebooks subfolder.
    folders = (Path.cwd(), Path.cwd() / 'datasets' / 'raw',
               Path.cwd().parent / 'datasets' / 'raw')
    for folder in folders:
        candidate = folder / filename
        if candidate.is_file():
            return candidate.resolve()
    searched = ', '.join(str(folder / filename) for folder in folders)
    raise FileNotFoundError(f'Missing required dataset {filename}. Searched: {searched}')

def output_root_for(data_file):
    folder = data_file.resolve().parent
    if folder.name == 'raw' and folder.parent.name == 'datasets':
        return folder.parent.parent
    return folder

DATA_FILE = locate_dataset('auto.csv')
DATA = DATA_FILE.parent
OUTPUT_ROOT = output_root_for(DATA_FILE)
print(f'Python {sys.version.split()[0]} | pandas {pd.__version__} | NumPy {np.__version__}')

Python 3.14.6 | pandas 3.0.3 | NumPy 2.4.6

## Read data

Read the original headerless file with `header=None`; otherwise the first automobile would be consumed as a header. The local CSV is an unchanged snapshot of the template's IBM source.

In [2]:
file_path = DATA / 'auto.csv'
assert file_path.is_file()
print('Input snapshot:', file_path.name)

Input snapshot: auto.csv

Utilize the Pandas method `read_csv()` to load the data into a dataframe.

In [3]:
df = pd.read_csv(file_path, header=None)
print(f'Loaded {len(df)} rows and {df.shape[1]} columns.')
assert df.shape == (205, 26)

Loaded 205 rows and 26 columns.

After reading the data set, we can use the <code>data_frame.head(n)</code> method to check the top n rows of the data frame, where n is an integer. Contrary to <code>data_frame.head(n)</code>, <code>data_frame.tail(n)</code> will show you the bottom n rows of the data frame.

In [4]:
# show the first 5 rows using dataframe.head() method
print("The first 5 rows of the dataframe") 
df.head(5)

The first 5 rows of the dataframe

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h1> Question #1: </h1>
<b>Check the bottom 10 rows of data frame "df".</b>
</div>

In [5]:
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,67.2,57.5,3034,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,67.2,56.2,2935,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,67.2,57.5,3042,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,188.8,67.2,56.2,3045,ohc,four,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,67.2,57.5,3157,ohc,four,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

<h3>Add Headers</h3>
<p>
Take a look at the data set. Pandas automatically set the header with an integer starting from 0.
</p>
<p>
To better describe the data, you can introduce a header. This information is available at:  <a href="https://archive.ics.uci.edu/ml/datasets/Automobile" target="_blank">https://archive.ics.uci.edu/ml/datasets/Automobile</a>.
</p>
<p>
Thus, you have to add headers manually.
</p>
<p>
First, create a list "headers" that include all column names in order.
Then, use <code>dataframe.columns = headers</code> to replace the headers with the list you created.
</p>

In [6]:
# create headers list
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
print("headers\n", headers)

headers
 ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

Replace headers and recheck our data frame:

In [7]:
df.columns = headers
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='str')

You can also see the first 10 entries of the updated data frame and note that the headers are updated.

In [8]:
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

Now, we need to replace the "?" symbol with NaN so the dropna() can remove the missing values:

In [9]:
df1 = df.replace('?', np.nan)
missing_counts = df1.isna().sum()
display(missing_counts[missing_counts.gt(0)].rename('Missing entries').to_frame())

                   Missing entries
normalized-losses               41
num-of-doors                     2
bore                             4
stroke                           4
horsepower                       2
peak-rpm                         2
price                            4

You can drop missing values along the column "price" as follows:

In [10]:
rows_before = len(df1)
df = df1.dropna(subset=['price']).copy()
print(f'Dropped {rows_before - len(df)} records without a price; retained {len(df)}.')
df.head(20)

Dropped 4 records without a price; retained 201.

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2710,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2765,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3055,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3230,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,197.0,70.9,56.3,3505,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,three,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,63.6,52.0,1874,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,63.6,52.0,1909,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

Removing a missing target avoids inventing price labels. This first lab keeps the other missing measurements for the cleaning exercise; dropping four records may still change the composition of the sample.

Here, `axis=0` means that the contents along the entire row will be dropped wherever the entity 'price' is found to be NaN

Now, you have successfully read the raw data set and added the correct headers into the data frame.

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h1> Question #2: </h1>
<b>Find the name of the columns of the dataframe.</b>
</div>

In [11]:
display(pd.Series(df.columns, name='Column name').to_frame())

          Column name
0           symboling
1   normalized-losses
2                make
3           fuel-type
4          aspiration
5        num-of-doors
6          body-style
7        drive-wheels
8     engine-location
9          wheel-base
10             length
11              width
12             height
13        curb-weight
14        engine-type
15   num-of-cylinders
16        engine-size
17        fuel-system
18               bore
19             stroke
20  compression-ratio
21         horsepower
22           peak-rpm
23           city-mpg
24        highway-mpg
25              price

<h2>Save Dataset</h2>
<p>
Correspondingly, Pandas enables you to save the data set to CSV. By using the <code>dataframe.to_csv()</code> method, you can add the file path and name along with quotation marks in the brackets.
</p>
<p>
For example, if you save the data frame <b>df</b> as <b>automobile.csv</b> to your local machine, you may use the syntax below, where <code>index = False</code> means the row names will not be written.
</p>

In [12]:
output_path = OUTPUT_ROOT / 'datasets/processed/M01/automobile.csv'
output_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(output_path, index=False)
print(f'Saved {len(df)} rows × {df.shape[1]} columns to {output_path.name}; no export index.')

Saved 201 rows × 26 columns to automobile.csv; no export index.

You can also read and save other file formats. You can use similar functions like **`pd.read_csv()`** and **`df.to_csv()`** for other data formats. The functions are listed in the following table:

<h2>Read/Save Other Data Formats</h2>

| Data Formate |        Read       |            Save |
| ------------ | :---------------: | --------------: |
| csv          |  `pd.read_csv()`  |   `df.to_csv()` |
| json         |  `pd.read_json()` |  `df.to_json()` |
| excel        | `pd.read_excel()` | `df.to_excel()` |
| hdf          |  `pd.read_hdf()`  |   `df.to_hdf()` |
| sql          |  `pd.read_sql()`  |   `df.to_sql()` |
| ...          |        ...        |             ... |

# Basic Insights from the Data set
<p>
After reading data into Pandas dataframe, it is time for you to explore the data set.<br>

There are several ways to obtain essential insights of the data to help you better understand it.
</p>

<h2>Data Types</h2>
<p>
Data has a variety of types.<br>

The main types stored in Pandas data frames are <b>object</b>, <b>float</b>, <b>int</b>, <b>bool</b> and <b>datetime64</b>. In order to better learn about each attribute, you should always know the data type of each column. In Pandas:
</p>

Returns a series with the data type of each column.

In [13]:
df.dtypes.rename('dtype').to_frame()

                     dtype
symboling            int64
normalized-losses      str
make                   str
fuel-type              str
aspiration             str
num-of-doors           str
body-style             str
drive-wheels           str
engine-location        str
wheel-base         float64
length             float64
width              float64
height             float64
curb-weight          int64
engine-type            str
num-of-cylinders       str
engine-size          int64
fuel-system            str
bore                   str
stroke                 str
compression-ratio  float64
horsepower             str
peak-rpm               str
city-mpg             int64
highway-mpg          int64
price                  str

Pandas 3 represents textual columns as `str`; earlier versions commonly displayed `object`. Several measurements, including price, remain textual because the raw file mixed numbers and `?`. Their numeric conversion belongs to Module 02.

<h2>Describe</h2>
If we would like to get a statistical summary of each column such as count, column mean value, column standard deviation, etc., use the describe method:

This method will provide various summary statistics, excluding <code>NaN</code> (Not a Number) values.

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
symboling,201.0,0.8408,1.2548,-2.0,0.0,1.0,2.0,3.0
wheel-base,201.0,98.7970,6.0664,86.6,94.5,97.0,102.4,120.9
length,201.0,174.2010,12.3222,141.1,166.8,173.2,183.5,208.1
width,201.0,65.8891,2.1015,60.3,64.1,65.5,66.6,72.0
height,201.0,53.7667,2.4478,47.8,52.0,54.1,55.5,59.8
curb-weight,201.0,2555.6667,517.2967,1488.0,2169.0,2414.0,2926.0,4066.0
engine-size,201.0,126.8756,41.5468,61.0,98.0,120.0,141.0,326.0
compression-ratio,201.0,10.1643,4.0050,7.0,8.6,9.0,9.4,23.0
city-mpg,201.0,25.1791,6.4232,13.0,19.0,24.0,30.0,49.0
highway-mpg,201.0,30.6866,6.8151,16.0,25.0,30.0,34.0,54.0

The numeric summary excludes missing entries. Counts refer to the 201 retained records, not the 205 original records. Use `include='all'` to also inspect textual columns.

In [15]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
symboling,201.0,NaN,NaN,NaN,0.8408,1.2548,-2.0,0.0,1.0,2.0,3.0
normalized-losses,164,51,161,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
make,201,22,toyota,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fuel-type,201,2,gas,181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
aspiration,201,2,std,165,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num-of-doors,199,2,four,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
body-style,201,5,sedan,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drive-wheels,201,3,fwd,118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
engine-location,201,2,front,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wheel-base,201.0,NaN,NaN,NaN,98.797,6.0664,86.6,94.5,97.0,102.4,120.9
length,201.0,NaN,NaN,NaN,174.201,12.3222,141.1,166.8,173.2,183.5,208.1
width,201.0,NaN,NaN,NaN,65.8891,2.1015,60.3,64.1,65.5,66.6,72.0
height,201.0,NaN,NaN,NaN,53.7667,2.4478,47.8,52.0,54.1,55.5,59.8
curb-weight,201.0,NaN,NaN,NaN,2555.6667,517.2967,1488.0,2169.0,2414.0,2926.0,4066.0
engine-type,201,6,ohc,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num-of-cylinders,201,7,four,157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
engine-size,201.0,NaN,NaN,NaN,126.8756,41.5468,61.0,98.0,120.0,141.0,326.0
fuel-system,201,8,mpfi,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bore,197,38,3.62,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stroke,197,36,3.40,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compression-ratio,201.0,NaN,NaN,NaN,10.1643,4.005,7.0,8.6,9.0,9.4,23.0
horsepower,199,58,68,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
peak-rpm,199,22,5500,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city-mpg,201.0,NaN,NaN,NaN,25.1791,6.4232,13.0,19.0,24.0,30.0,49.0
highway-mpg,201.0,NaN,NaN,NaN,30.6866,6.8151,16.0,25.0,30.0,34.0,54.0
price,201,186,16500,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For text columns, `count`, `unique`, `top` and `freq` describe the observed strings. A blank statistic in this mixed summary means that statistic does not apply to that column's type.

# Question #3

Select the `length` and `compression-ratio` columns using `df[['length', 'compression-ratio']]`, then apply `describe()` to obtain their descriptive statistics.

In [16]:
df[['length', 'compression-ratio']].describe()

         length  compression-ratio
count  201.0000           201.0000
mean   174.2010            10.1643
std     12.3222             4.0050
min    141.1000             7.0000
25%    166.8000             8.6000
50%    173.2000             9.0000
75%    183.5000             9.4000
max    208.1000            23.0000

Length is a numerical measurement in inches, while compression ratio is dimensionless. A large mean–median gap or high maximum is a reason to inspect the distribution, not an automatic reason to remove records.

<h2>Info</h2>
You can also use another method to check your data set:

It provides a concise summary of your data frame. 

This method prints information about a data frame including the index dtype and columns, non-null values and memory usage.

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  164 non-null    str
 2   make               201 non-null    str
 3   fuel-type          201 non-null    str
 4   aspiration         201 non-null    str
 5   num-of-doors       199 non-null    str
 6   body-style         201 non-null    str
 7   drive-wheels       201 non-null    str
 8   engine-location    201 non-null    str
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    str
 15  num-of-cylinders   201 non-null    str
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    str
 18  bore               197 non-null    str
 19  stroke             197 non-null    str
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    str
 22  peak-rpm           199 non-null    str
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 55.2 KB

## Original teaching-material credits

**Author:** [Joseph Santarcangelo](https://www.linkedin.com/in/joseph-s-50398b136/).

**Other contributors:** Mahdi Noorian, Bahare Talayian, Eric Xiao, Steven Dong, Parizad, Hima Vasudevan, Fiorella Wenver, Yi Yao, and Abhishek Gagneja.

© IBM Corporation 2023. All rights reserved.

## Tool acknowledgement

OpenAI Codex assisted with code completion, debugging and explanation drafting. Numerical results and figures were generated by executing the notebook in the recorded local Python environment. The collaborators are responsible for reviewing the analysis and submitted material. [OpenAI Codex](https://openai.com/codex/) (accessed 15 September 2026).